nulib/donut

Gemfile, Gemfile.lock, spec/factories/users.rb, spec/features/create_image_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/database_cleaner.rb, spec/support/features/session_helpers.rb, spec/support/fedora_cleaner.rb, spec/support/workflow_resetter.rb
This PR makes changes to the Gemfile, make sure to run `bundle install` locally.
=> Refactor RSpec configuration, add factories, update specs

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/sessions_controller.rb, app/models/user.rb, config/initializers/omniauth.rb, config/routes.rb, db/migrate/20170620232206_add_username_to_users.rb, db/schema.rb, spec/factories/users.rb
This PR adds omniauth signon via Northwestern University's SSO service. Make sure to run `bundle install` locally to pick up changes to the `Gemfile`.
Set up dev authentication using [instructions in the wiki](https://github.com/nulib/donut/wiki/Authentication-setup-for-dev-environment).
=> Add omniauth support

Gemfile, Gemfile.lock, README.md, app/models/ability.rb, app/models/user.rb, config/routes.rb, db/migrate/20170621193315_user_roles.rb, db/schema.rb, lib/tasks/add_admin_user.rake, lib/tasks/generate_roles.rake, spec/ability/roles_spec.rb, spec/factories/images.rb, spec/factories/users.rb
Run `bundle install` and `rake db:migrate` to test locally. A few steps to add yourself as an admin user (also in the README):
1. Sign in to the app at http://devbox.library.northwestern.edu/
1. In a terminal run `rake generate_roles`
1. Then run `rake add_admin_role` (this uses `User.last` which will likely be you b/c first step)
1. That's it you're an admin!
=> Add roles and update README

Gemfile, Gemfile.lock, config/application.rb, config/environments/production.rb, config/initializers/hyrax.rb, lib/active_job/queue_adapters/better_active_elastic_job_adapter.rb, spec/lib/active_job/queue_adapters/better_active_elastic_job_adapter_spec.rb
Run `bundle install` to pick up changes to the Gemfile.
=> Add active_elastic_job gem and BetterActiveElasticJobAdapter class

app/assets/stylesheets/donut/_main.scss, app/assets/stylesheets/donut/layout/_header.scss, app/assets/stylesheets/donut/layout/_nav.scss, app/assets/stylesheets/donut/layout/_sidebar.scss, app/assets/stylesheets/nuwebcomm/styles.scss
This should remove a bulk of the NU branding issues which were being seen between the Header and Footer.  I tried to navigate all through the app, but very l likely I'm missing some stuff.  If anyone just wants to log an issue if you come across something and assign to me, I can make another pass through this on Thursday.
=> Remove internal appliaction NU branding

app/models/image.rb, config/initializers/hydra_config.rb, config/locales/en.yml, config/routes.rb
Fixes #46 
There's still one more deprecation warning that we'll need to get rid of in #48, but that's not part of this PR
=> Fix deprecations#46

README.md
=> upgrade README for minio

Gemfile, Gemfile.lock, spec/ability/roles_spec.rb, spec/factories/collections.rb, spec/factories/file_sets.rb, spec/factories/images.rb, spec/factories/users.rb, spec/features/create_image_spec.rb, spec/features/dashboard/all_works_spec.rb, spec/forms/hyrax/image_form_spec.rb, spec/presenters/file_set_presenter_spec.rb, spec/presenters/hyrax/image_presenter_spec.rb, spec/rails_helper.rb
find `factory_girl` replace with `factory_bot` (more or less)
=> deprecation warnings were annoying me

.ebextensions/02_install.config
=> Make $RAILS_ROOT/bin/* executable

.ebextensions/01_packages.config
These changes will get rid of some of the issues we're seeing on AWS. We'll probably run into more, but we've got to clear these out to proceed.
=> help test derivatives on AWS

lib/importer/factory/object_factory.rb
=> allowing AWS importer to get further

app/models/schema/administrative.rb
Updated constant for slightly more clarity.
=> Change Schema::Administrative::REVIEWED_STRING to REVIEWED_STATUS

app/actors/hyrax/actors/create_with_remote_files_actor.rb
overriding a hyrax actor so we can stop another layer of encoding happening
=> Override remote actor

app/views/records/edit_fields/_genre.html.erb, spec/views/records/edit_fields/_genre.html.erb_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/313
=> genre now querying authority, specs written

app/views/records/edit_fields/_technique.html.erb, spec/views/records/edit_fields/_technique.html.erb_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/310 
I believe i'm querying the correct authority based on the spreadsheet, but please make sure!
=> technique now querying authority, specs for new authority

app/views/records/edit_fields/_creator_role.html.erb, spec/views/records/edit_fields/_creator_role.html.erb_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/312
I'm guessing this is the correct authority based on the issue
=> creator role querying authority, specs added

app/views/records/edit_fields/_contributor_role.html.erb, spec/views/records/edit_fields/_contributor_role.html.erb_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/315
=> added authority querying for contributor role

app/views/records/edit_fields/_language.html.erb, spec/views/records/edit_fields/_language.html.erb_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/316
=> added authority querying for language

app/views/records/edit_fields/_preservation_level.html.erb
fixes https://github.com/nulib/next-generation-repository/issues/329
=> restricting preservation level entry

app/views/records/edit_fields/_contributor.html.erb, app/views/records/edit_fields/_subject.html.erb, config/locales/hyrax.en.yml
fixes https://github.com/nulib/next-generation-repository/issues/330
new pr because squashing
=> fields with authority drop downs update correctly now

app/services/hyrax/creator_authorities.rb, app/views/records/edit_fields/_creator.html.erb, config/authorities/creators.yml, config/locales/hyrax.en.yml
Fixes: https://github.com/nulib/donut/issues/129
=> Adding authority select and autocomplete for creator

spec/models/image_spec.rb, spec/schema/administrative_spec.rb, spec/support/shared_examples/a_model_with_admin_schema.rb, spec/support/shared_examples/a_model_with_hyrax_basic_metadata.rb, spec/support/shared_examples/a_model_with_image_metadata.rb
- Add image metadata shared example
- Add hyrax basic metadata shared example
- Finish admin metadata shared example
=> Better shared examples

config/initializers/riiif.rb
https://github.com/nulib/repodev_planning_and_docs/issues/130
=> Initialize riiif to use graphicsmagick

lib/importer/factory/object_factory.rb
* Default is 15 minutes - too short for batch. Increase to maximum. (1 week)
=> Increase expiration of presigned url

config/initializers/browse_s3.rb, config/routes.rb
Resolves nulib/next-generation-repository#323
=> Enable S3 dropbox via BrowseEverything

.travis.yml, Gemfile, Gemfile.lock, README.md, config/settings/development.yml, config/settings/test.yml, docker-compose.yml, lib/tasks/donut.rake, lib/tasks/s3_tasks.rake
Adds a completely dockerized fedora, solr, cantaloupe, and minio environment for development, and updates the README with instructions for use.
=> Add dockerized dev environment

docker-compose.yml
=> Add redis to docker stack

app/models/concerns/caching_fetcher.rb, app/models/controlled_vocabularies/base.rb, app/models/controlled_vocabularies/contributor_role.rb, app/models/controlled_vocabularies/genre.rb, app/models/controlled_vocabularies/language.rb, app/models/controlled_vocabularies/style_period.rb, app/models/controlled_vocabularies/technique.rb, config/environments/development.rb, config/initializers/hyrax.rb, config/initializers/location_caching.rb
Add authority label caching; turn off NestingIndexer
=> QA caching

docker-compose.test.yml, docker-compose.yml, lib/importer/factory/object_factory.rb
- Replaces minio with localstack
- Removes minio workaround in `lib/importer/factory/object_factory.rb`
=> Replace minio with localstack

app/models/solr_document.rb, app/presenters/hyrax/image_presenter.rb
- Add `_label` to Hyrax::ImagePresenter::TERMS marc relators
- Add `_label` to SolrDocument attributes and methods
=> Add _label to Hyrax::ImagePresenter::TERMS and SolrDocument 

app/models/batch_item.rb
* Write full error to worker log so we can troubleshoot
* Display error to user about model missing or incorrect
=> Log batch item errors

app/models/image.rb
* creator not controlled property yet so this is causing a confusing error.
=> creator not controlled property

spec/batch/importer/factory/image_factory_spec.rb, spec/models/batch_item_spec.rb, spec/rails_helper.rb, spec/support/database_cleaner.rb, spec/support/fedora_cleaner.rb
Ensure database_cleaner loads first
Reset autoincrement counters when using postgres
Only recreate admin sets on tests that require it
=> Make specs run faster and support repeated runs

app/models/batch_item.rb
* checks solr for existing Image with accession_number and skips record in batch if exists.
partially addresses #https://github.com/nulib/next-generation-repository/issues/438
Still need to implement unique accession number through the UI so this check will likely move out of `batch_item.rb` to somewhere it can be reused. However, this check will substantially change the user exerience when running/rerunning batches so wanted it to be in place while we are testing because it will likely bring to light some other issues we need to address.
=> dont allow duplicate accession numbers through batch

app/models/concerns/resource_type_validator.rb, app/models/image.rb, spec/models/resource_type_validator_spec.rb
fixes part of https://github.com/nulib/next-generation-repository/issues/483
i figured i'd go with smaller PRs with a feature in each one
=> add resource_type validator and specs

app/models/concerns/preservation_level_validator.rb, app/models/image.rb, app/services/hyrax/preservation_level_authorities.rb, config/authorities/preservation_level.yml, spec/factories/images.rb, spec/models/image_spec.rb, spec/models/preservation_level_validator_spec.rb
fixes another part of https://github.com/nulib/next-generation-repository/issues/483
=> added preservation level validation and a default value

app/models/controlled_vocabularies/base.rb
co-authored-by: Michael B. Klein <mbklein@gmail.com>
=> include rdf reader, strip leading zeroes from uri

app/indexers/donut/collection_indexer.rb, app/indexers/image_indexer.rb, spec/indexers/image_indexer_spec.rb
Fixes https://github.com/nulib/next-generation-repository/issues/510
* adds iiif urls for each member FileSet to solr doc for Image
=> index iiif urls for filesets on image

app/models/concerns/hyrax/file_set/characterization.rb, app/models/schemas/northwestern_image_schema.rb, app/models/solr_document.rb, app/models/vocab/donut.rb, app/presenters/hyrax/characterization_behavior.rb, app/services/donut/characterization_service.rb, config/initializers/delegate_metadata_to_file_set_presenter.rb, config/initializers/extend_file_set_indexer.rb, spec/models/solr_document_spec.rb, spec/services/donut/characterization_service_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/494
=> added profile description as per dan zellners request

app/batch/importer/factory/object_factory.rb, config/initializers/hyrax.rb
fixes https://github.com/nulib/next-generation-repository/issues/497 (in conjunction with upgrading to hyrax 2.1.0rc3, which has already happened) 
I tried this out locally and it worked successfully
=> re-enabling nested indexing

.travis.yml, Gemfile, Gemfile.lock
part of https://github.com/nulib/next-generation-repository/issues/66 and https://github.com/nulib/next-generation-repository/issues/164
to check and see if virus scanning is working, you basically need to check for the absence of this error message https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/virus_scanner.rb#L46
=> adding clamav to aws group

.docker-stack/nextgen-development/docker-compose.yml, .docker-stack/nextgen-test/docker-compose.yml, Gemfile, Gemfile.lock, app/models/image.rb, config/initializers/common_indexer_config.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, spec/models/image_spec.rb
Start indexing to ElasticSearch
=> Common indexer

app/services/common_indexers/image.rb
change from `/info.json` to `/manifest.json`
=> index correct url for iiif manifest

app/models/collection.rb, app/services/common_indexers/collection.rb, spec/models/collection_spec.rb
* Adds `to_common_index` to Collections as the front end needs to display collection info
=> index collections in elastic search index

app/batch/importer/csv_importer.rb
Co-authored-by: Brendan Quinn <brendan.quinn@northwestern.edu>
=> Handles ArgumentError for invalid UTF-8 byte in .csv

app/models/solr_document.rb
Fixes: https://github.com/nulib/next-generation-repository/issues/635
=> update accession_number in solr_document.rb

app/services/common_indexers/collection.rb
Partially fixes https://github.com/nulib/next-gen-front-end-react/issues/90
=> Add keyword to collection indexing for front end

.docker-stack/nextgen-development/docker-compose.yml, Gemfile, Gemfile.lock, lib/tasks/donut.rake, lib/tasks/elasticsearch.rake
`bundle exec rake es:reinit` will (re)initialize the index using the most up to date schema.
=> Create a rake task to initialize (or reinitialize) the elasticsearch index

Gemfile, Gemfile.lock, app/services/common_indexers/base.rb, app/services/common_indexers/image.rb
** Corresponding changes are already in common-indexer master
* remove creators ( `nul_creator` and `creator`) from contributors indexing
* index  `nul_creator` and `creator` as creators
* Add `nul_contributor` to contributors indexing
* Index (and facet) "Label (Role)" for contributors
=> index role on contributor label and facet

app/services/common_indexers/image.rb
fixes https://github.com/nulib/next-generation-repository/issues/604
=> index the text of the rights statement

.docker-stack/nextgen-development/docker-compose.yml, .docker-stack/nextgen-test/docker-compose.yml, Gemfile, config/blacklight.yml, config/initializers/aws_sdk.rb, config/settings/development.yml, config/settings/test.yml, config/solr.yml, lib/tasks/docker.rake, lib/tasks/donut.rake
Use the [devstack](http://github.com/nulib/devstack) container environment for development
=> Use devstack

app/assets/javascripts/hyrax/autocomplete.es6, app/controllers/catalog_controller.rb, app/forms/hyrax/image_form.rb, app/models/image.rb, app/models/schemas/common_metadata.rb, app/models/solr_document.rb, app/presenters/hyrax/image_presenter.rb, app/services/common_indexers/image.rb, app/services/hyrax/collector_authorities.rb, app/services/hyrax/distributor_authorities.rb, app/services/hyrax/donor_authorities.rb, app/services/hyrax/musician_authorities.rb, app/services/hyrax/transcriber_authorities.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/views/images/edit_fields/_collector.html.erb, app/views/images/edit_fields/_distributor.html.erb, app/views/images/edit_fields/_donor.html.erb, app/views/images/edit_fields/_musician.html.erb, app/views/images/edit_fields/_transcriber.html.erb, config/authorities/collectors.yml, config/authorities/distributors.yml, config/authorities/donors.yml, config/authorities/musicians.yml, config/authorities/transcribers.yml, config/locales/hyrax.en.yml, spec/support/shared_examples/a_model_with_common_metadata.rb
fixes https://github.com/nulib/next-generation-repository/issues/628
=> adding in jens requested roles

app/services/common_indexers/base.rb, app/services/common_indexers/image.rb, spec/factories/images.rb
fixes https://github.com/nulib/next-generation-repository/issues/784
=> fix indexing of String date_modified and date_uploaded dates

app/indexers/donut/collection_indexer.rb, app/models/collection.rb, app/services/common_indexers/admin_set.rb, app/services/common_indexers/collection.rb, config/initializers/donut_collection_indexer.rb, spec/indexers/donut/collection_indexer_spec.rb, spec/models/admin_set_spec.rb, spec/models/collection_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/783
=> 783 collections date modified

.rubocop.yml, app/services/common_indexers/base.rb
fixes https://github.com/nulib/next-generation-repository/issues/751
=> Index uncontrolled contributor as (Contributor)

app/controllers/validation_controller.rb
fixes https://github.com/nulib/next-generation-repository/issues/767
=> Skip in_work_ids during new work validation

app/services/common_indexers/image.rb
fixes https://github.com/nulib/next-generation-repository/issues/804
=> cleanup Elasticsearch representative_file and thumbnail indexing

app/services/iiif_manifest_service.rb, spec/services/iiif_manifest_service_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/766
=> don't write/show manifests for private works

app/jobs/attach_files_to_work_job.rb
Apply samvera/hyrax@52380581f27da9af65fc44b76c1ab837aea815a0 to donut without upgrading the rest of hyrax
=> Backport “Quick fix for AttachFileToWorksJob idempotency”

app/services/donut/vocabulary_validation_service.rb, spec/services/donut/vocabulary_validation_service_spec.rb
fixes https://github.com/nulib/next-generation-repository/issues/717
=> Fix mistake in regex in names and subjects expressions

Gemfile, Gemfile.lock, config/environments/production.rb
fixes https://github.com/nulib/next-generation-repository/issues/864
Pull from Arch:
https://github.com/nulib/institutional-repository/commit/8a2b1533c945747bce2d74fdc2f65011f1ee497e
https://github.com/nulib/institutional-repository/commit/10aa2333b7c2c08cb0915def2b78996ffb46a348
=> Reduce noise in logs

Gemfile, Gemfile.lock
fixes https://github.com/nulib/next-generation-repository/issues/879
=> Use common indexer v0.3.1 with all_titles and all_subjects

Gemfile.lock, app/services/common_indexers/image.rb
fixes https://github.com/nulib/next-gen-front-end-react/issues/293
=> Use common_indexer v0.3.3 for full_text indexing

app/models/user.rb, app/views/_user_util_links.html.erb, config/initializers/ezid_credentials.rb, config/routes.rb
Co-authored-by: Brendan Quinn <brendan-quinn@northwestern.edu>
=> Fix deprecation warnings

Gemfile, Gemfile.lock
Fixes https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/
=> Upgrade bootstrap-sass to fix vulnerability

.travis.yml, Gemfile, Gemfile.lock, config/initializers/_aws_config.rb, config/initializers/browse_s3.rb, config/initializers/common_indexer_config.rb, config/settings/development.yml, config/settings/test.yml
fixes https://github.com/nulib/next-generation-repository/issues/910
=> Sign Elasticsearch requests

app/controllers/catalog_controller.rb
Fixes https://github.com/nulib/next-generation-repository/issues/951
Co-authored-by: Karen Shaw <karendid@gmail.com>
=> Use post instead of get for solr queries

app/models/controlled_vocabularies/base.rb
fixes https://github.com/nulib/next-generation-repository/issues/944
=> Fetch FAST labels from the correct URL

app/jobs/create_pyramid_tiff_job.rb, config/settings/development.yml
There's no way to test this locally at this point, but it would be great if this got a serious once-over from @mbklein and @kdid before we deploy anything to staging.
=> Replace CreatePyramidTiffJob implementation with lambda invocation

app/services/common_indexers/image.rb
partially fixes https://github.com/nulib/repodev_planning_and_docs/issues/213
=> Add member_ids to Elasticsearch index for Images

app/models/collection.rb
=> Revert the change to conditionally common index collections

README.md, app/services/iiif_manifest_service.rb, spec/services/iiif_manifest_service_spec.rb
`iiif_manifest` gem expects a string
=> Make sure manifest_url implementation returns string

.rubocop.yml, .rubocop_todo.yml, app/services/donut/migration_service.rb, config/settings/development.yml, lib/tasks/migration.rake, spec/services/donut/migration_service_spec.rb
- Run the task: `EXPORT_LIMIT=1 OVERWRITE=true bundle exec rake migration:run`
- Files should end up in the bucket `dev-export-donut-meadow-manifests`
- Donut::MigrationService spec should pass, only tests the data conversion not the S3 upload so far.
=> Initial implementation for Donut::MigrationService with its rake task

app/services/donut/characterization_service.rb
Current behavior:
```ruby
Exiftool.new("/Users/brendan/Downloads/inu-wint-21-2-5.tif", '-a -u -g1').to_hash.to_json'
JSON::GeneratorError: source sequence is illegal/malformed utf-8
from /Users/brendan/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/core_ext/object/json.rb:36:in `to_json'
```
New behavior:
```ruby
Exiftool.new('/Users/brendan/Downloads/inu-wint-21-2-5.tif', '-a -g1').to_json
{
"source_file": '/Users/brendan/Downloads/inu-wint-21-2-5.tif',
"exif_tool": { "ExifToolVersion": 10.65 },
"system": {
"FileName": 'inu-wint-21-2-5.tif',
"Directory": '/Users/brendan/Downloads',
"FileSize": '121 MB',
"FileModifyDate": '2021:01:28 10:58:04-06:00',
"FileAccessDate": '2021:01:28 10:59:59-06:00',
"FileInodeChangeDate": '2021:01:28 …
```
=> Do not use the '-u' option to extract unknown EXIF tags during characterization

app/services/donut/migration_service.rb, spec/services/donut/migration_service_spec.rb
- Changes to `Donut::MigrationService`
- Add `collection_id` to core work metadata, with test coverage
- Fix shape of `library_unit` hash to match Meadow, with test coverage
- Upload each manifest to S3 earlier in the process to improve overall migration
- `Logger.warn` instead of `raise` if an `Image` is not found to prevent unnecessary halting of the migration
=> Add collection_id to export manifest and upload to S3 earlier

app/services/donut/migration_service.rb
- Skip processing existing manifests in export bucket
- Fixes file_set original_filename bug
=> Skip existing manifests in S3 and fix file_set original_filename bug

app/services/donut/migration_service.rb, spec/services/donut/migration_service_spec.rb
Sorry about the formatting changes, I installed `prettier-ruby` and it did a number on the files I modified 😱
=> Add alternate_title and rights_statement to the migration
