nulib/donut

README.md
config/initializers/hyrax.rb
config/oclcts-authorities.yml
config/settings.yml

For local development, add a registered geonames user to `settings.local.yml` with the `geonames_username` key, e.g. `geonames_username: geonames_test_user`. This is just a configuration for built-in Hyrax functionality in web forms using `questioning_authority` functionality that relies upon the Geonames service, e.g. the `Location` field in the Images work type.
Note: the user must have the "free web service" option enabled from http://www.geonames.org/manageaccount

Add geonames configuration for questioning_authority functionality

---

app/assets/stylesheets/application.scss
vendor/assets/stylesheets/select2.css

@kdid @bmquinn @davidschober  This should fix #176 (https://github.com/nulib/next-generation-repository/issues/176) and #177 (https://github.com/nulib/next-generation-repository/issues/177). 
The problem was that `*=require select2` in `app/assets/stylesheets/hyrax.scss` is not actually pulling the file into the application for whatever reason.  The `select2.js` file is getting brought in via the `select2-rails` gem, but it's `select2.css` dependency was not.
So, this solution gets it working by including a hard dependency for `select2.css`in Donut.  The right way to fix would be to eventually pull it via the gem, if anyone's feeling ambitious.

Add select2.css directly to the donut application

---

Gemfile
Gemfile.lock
app/models/image.rb
app/models/solr_document.rb
app/presenters/hyrax/image_presenter.rb
app/services/ark_minting_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/initializers/ezid_credentials.rb
spec/factories/images.rb
spec/forms/hyrax/image_form_spec.rb
spec/models/image_spec.rb
spec/presenters/hyrax/image_presenter_spec.rb

Adds ARK minting support for Image works using an `after_save` callback.
Production environment needs to set the following ENV variables: `EZID_DEFAULT_SHOULDER, EZID_USER, EZID_PASSWORD, EZID_HOST, EZID_PORT, EZID_USE_SSL`
`ezid-client` added to the Gemfile, make sure to run `bundle install` locally.

Add ark minting for Image works

---

app/forms/hyrax/image_form.rb
app/models/image.rb
spec/forms/hyrax/image_form_spec.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/216
batch upload form just includes the default fields.

remove accession number from required fields

---

config/initializers/aws-sdk.rb
lib/importer/csv_importer.rb
spec/lib/importer/csv_importer_spec.rb

- Removes @model parameter from Importer::CSVImporter#initialize
- Refactors Importer::CSVImporter spec to use aws-sdk functionality

Remove param and green up csv_importer_spec

---

.rubocop.yml
spec/lib/importer/csv_parser_spec.rb

Not much to add beyond PR title. I'm not a big fan of having to add `rubocop:disable RSpec/ExampleLength` to `spec/lib/importer/csv_parser_spec.rb:13` but it's not a difficult refactor in the near future.

Refactor csv_parser_spec to read csv file and update specs

---

spec/lib/importer/factory/image_factory_spec.rb

- Fixes local test environment failing specs for Importer::Factory::ImageFactory

Change specs from start_with to include for remote_files attribute

---

lib/importer/factory/object_factory.rb

fixes #77 
so here's a deceptively simple fix to a weird issue. Basically the AWS gem's presigned url call returns an encoded URL, but later on in the actor stack in hyrax the url gets encoded again and messes with the url and it no longer resolves. 
The proper, long term fix would be to handle both encoded and non-encoded urls in hyrax, but that would require more time and work. 
So for right now i just decode the url and pass it along the actor stack, which seems to work fine.

unencoding an encoded url

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/forms/hyrax/image_form.rb
app/models/image.rb
app/models/schema/administrative.rb
app/models/solr_document.rb
app/models/vocab/donut.rb
app/presenters/hyrax/image_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/forms/hyrax/image_form_spec.rb
spec/models/image_spec.rb
spec/models/solr_document_spec.rb
spec/schema/administrative_spec.rb
spec/support/shared_examples/a_model_with_admin_schema.rb

- Adds `Schema::Administrative` module, which is included in the `Image` model
- Adds `hyrax-spec` gem to Gemfile
- Adds `Vocab::Donut` module for local RDF property definitions
- Adds 'a model with admin schema' shared example
- Updates `Image` form and presenter to include administrative metadata

Administrative metadata

---

.ebextensions/01_packages.config

So it looks like we have to download the binaries from harvard's hosting, that github repo only contains source code. I ran into this ticket https://github.com/harvard-lts/fits/issues/149 which explains it in more detail
it does look like their hosting is up and running as of today though, i just tested it out and i'm not getting the error anymore

this release has binaries in it

---

.rubocop.yml

the `create_with_remote_files_actor` file is taken from hyrax so we could change the settings on one line, but it's causing rubocop to throw up some errors. We should probably just ignore it for now (and until we can figure out a better, long term fix for overriding this file) 
Fixes #102

ignore the hyrax override file

---

app/assets/javascripts/application.js
app/assets/javascripts/hyrax/authority_select.es6
app/assets/javascripts/hyrax/editor.es6
app/services/hyrax/subject_authorities.rb
app/views/records/edit_fields/_subject.html.erb
config/authorities/subjects.yml
config/initializers/hyrax.rb
config/locales/hyrax.en.yml

- Overrides `app/assets/javascripts/hyrax/authority_select.es6` and `app/assets/javascripts/hyrax/authority_select.es6` from Hyrax to initialize AuthoritySelect fields.
- Adds autocomplete field and associated authority select field for subject.

Add authority select dropdown for subject

---

app/services/hyrax/contributor_authorities.rb
app/views/records/edit_fields/_contributor.html.erb
config/authorities/contributors.yml
spec/views/records/edit_fields/_contributor.html.erb_spec.rb

fixes https://github.com/nulib/next-generation-repository/issues/314
It looks like QA doesn't have out of the box support for viaf, but it looks like QA supports various ways of implementing other authorities. I created https://github.com/nulib/next-generation-repository/issues/324 to track adding VIAF

adding contributor multi authority field, but missing viaf

---

app/models/schema/administrative.rb
app/views/records/edit_fields/_preservation_level.html.erb

Fixes bug with preservation level not being saved on form submission, because it was sending a single-valued string to a multi-valued property. Changed the property to `multiple: false` to fix the issue.

Make preservation level single-valued

---

Gemfile
Gemfile.lock
config/boot.rb

Let's make the application boot more quickly! Uses the [bootsnap gem](https://github.com/Shopify/bootsnap) which will be installed by default in Rails 5.2.0.

Add bootsnap gem for faster load times

---

config/initializers/hyrax.rb

Temporarily disabled while derivative issue is sorted out via https://github.com/nulib/repodev_planning_and_docs/issues/132

Set config.iiif_image_server to false

---

app/assets/javascripts/hyrax/autocomplete.es6
app/controllers/catalog_controller.rb
app/forms/hyrax/image_form.rb
app/models/controlled_vocabularies/language.rb
app/models/image.rb
app/models/schemas/administrative.rb
app/models/schemas/core_metadata.rb
app/models/schemas/generated_resource_schema_strategy.rb
app/models/solr_document.rb
app/presenters/hyrax/image_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_language.html.erb
spec/models/image_spec.rb
spec/schemas/administrative_spec.rb
spec/support/shared_examples/a_model_with_admin_schema.rb
spec/support/shared_examples/a_model_with_nul_core_metadata.rb

- Overrides Hyrax's basic_metadata language property, in order to add controlled vocabulary functionality
- Renames `app/models/schema` to `app/models/schemas` for consistency
- Adds `a_model_with_nul_core_metadata.rb` shared example

Use controlled vocabulary for language property

---

app/models/controlled_vocabularies/contributor_role.rb
app/models/controlled_vocabularies/language.rb

Fixes deprecation warning `[DEPRECATION] URI#to_hash is deprecated, use URI#to_h instead.` with solution described in https://github.com/ruby-rdf/rdf/issues/341

Fix RDF::URI deprecations using class method instantiation

---

app/models/schemas/core_metadata.rb
spec/models/image_spec.rb
spec/support/shared_examples/a_model_with_nul_core_metadata.rb

Fixes https://github.com/nulib/next-generation-repository/issues/298
- Overrides keyword predicate in `Schemas::CoreMetadata`
- Updates `a_model_with_nul_core_metadata.rb` shared example
- Excludes `:keyword` from 'a model with hyrax basic metadata' in `image_spec`

Override keyword predicate

---

Gemfile.lock

Fixes the error described in this issue: https://github.com/ffi/ffi/issues/608

Update ffi to latest, fixing bundle install error

---

app/forms/hyrax/image_form.rb
app/models/image.rb
app/models/solr_document.rb
app/presenters/hyrax/image_presenter.rb
spec/factories/images.rb
spec/forms/hyrax/image_form_spec.rb
spec/models/solr_document_spec.rb
spec/support/shared_examples/a_model_with_image_metadata.rb

Fixes https://github.com/nulib/next-generation-repository/issues/393
- Removes `related_url_label` property from the Image model and references to the property in the solr_document model, presenter, forms and specs.

Remove related_url_label property from the Image model, forms, specs

---

lib/importer/csv_parser.rb

Currently, trying to run batch with a value for any of our single valued fields (accession_number, call_number, etc) causes the entire batch to fail and enter a retry loop
```
E, [2018-02-27T17:02:58.642000 #24565] ERROR -- : [f10a5ccd-bb26-47a3-9a63-fc319334f575] [ActiveJob] [S3ImportJob] [65858cc0-bcfb-4514-93ed-6accbc3b90f4] Error performing S3ImportJob (Job ID: 65858cc0-bcfb-4514-93ed-6accbc3b90f4) from BetterActiveElasticJob(batch_ingest) in 19367.06ms: ArgumentError (You attempted to set the property `accession_number' of  to an enumerable value. However, this property is declared as singular.):
```

Handle single valued properties

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
README.md
config/settings/test.yml
docker-compose.test.yml
lib/tasks/donut.rake

- Uses docker containers instead of `solr_wrapper` and `fcrepo_wrapper`
- Adds rake tasks for starting/stopping/cleaning dev and test server stacks
- Updates README to reflect those changes

Dockerize test environment

---

Gemfile
Gemfile.lock
docker-compose.test.yml
docker-compose.yml
lib/docker_controller.rb
lib/tasks/donut.rake

Instead of waiting 20 seconds for services to come up, add actual health checks to the `docker-compose` files and use them to determine if/when the services are ready. Also do a better job of trapping `SIGINT` and making sure services come down on exit.

Add docker health checks and saner waits

---

Gemfile
bin/rake
config/database.yml
config/redis.yml
config/settings/development.yml
config/settings/test.yml
db/schema.rb
docker-compose.test.yml
docker-compose.yml
lib/docker_controller.rb
lib/donut/database_creator.rb
lib/tasks/add_admin_user.rake
lib/tasks/donut.rake
lib/tasks/s3_tasks.rake

More improvements to the dockerized dev environment, including:
- a `rake donut:seed` task that:
- creates/migrates the DB
- creates the collection types
- creates the default admin set
- imports the default workflows
- activates the default workflows
- sets up and populates the S3 bucket
- creates a user and makes it an admin (if `ADMIN_USER` and `ADMIN_EMAIL` are specified)
- a postgres container and the `config/database.yaml` to use it
- a workaround for a stupid ActiveRecord behavior that wants to create the test database in dev mode, which doesn't work with our dockerized environment

More dev perks

---

app/forms/hyrax/image_form.rb

Fixed typo that prevented language fields from being removed in edit form

fix typo on permitted params

---

app/batch/importer/csv_importer.rb
app/batch/importer/csv_parser.rb
app/jobs/s3_import_job.rb
spec/batch/importer/csv_parser_spec.rb

* If there is a failure at the batch level during header validation, raise and rescue a custom error
* UI will display a batch item error for row number zero with details about the validation problem. 
* The Job does not retry

handle batch level validation failure

---

config/initializers/override_file_set_actor.rb

Fixes https://github.com/nulib/next-generation-repository/issues/380 
Fixes https://github.com/nulib/next-generation-repository/issues/327
Override the `FileSetActor.attach_to_work` so that we can add a `file_set.reload`
Otherwise (dev environment + UI upload only) the actor has the wrong copy of the file_set and the characterization info is overwritten in solr. This is causing previews and UniversalViewer not to display on the work page and the characterization info not to display on the FileSet page until the file set is reindexed.
I was not able to reproduce in Hyrax.

override FileSetActor to reload file_set

---

config/initializers/override_file_set_actor.rb

* Address`ActiveFedora::ObjectNotFoundError: Can't reload an object that hasn't been saved` that this override caused in batch

make sure file_set is persisted before reload

---

app/batch/importer/csv_parser.rb

Replaces `^` with `\A`
* The `^` seems to remove problem characters at the start of all lines, using `\A` just removes from the start of the file.  This is causing a problem if the first property in a data row is blank (like a blank accession number) which means the first character in that row is a comma, which is removed and then the data row is off.

fix comma first character in data row bug

---

app/models/batch_item.rb
app/views/batches/_error_row.html.erb
spec/models/batch_item_spec.rb

Fixes https://github.com/nulib/next-generation-repository/issues/480
* makes sure spreadsheet values for properties defined as controlled on the Image model are uri's
* fixes bug where `<br />` in the batch_item's error_row is escaped and displayed as string
* updates spec in batch_item_spec.rb for new validation

validates controlled properties in batch contain uris

---

Gemfile
Gemfile.lock
config/initializers/retry.rb
lib/donut/retry.rb
spec/lib/donut/retry_spec.rb

Monkeypatches `Ldp::Client` and `RSolr::Client` to wrap their web service calls in [Retryable](http://rdoc.info/gems/retryable) blocks

Add smart, configurable retry to Ldp and RSolr

---

README.md
lib/tasks/donut.rake

Run `rake donut:add_admin_role ADMIN_USER[your NetID]` or `rake donut:seed ADMIN_USER=[your NetID] ADMIN_EMAIL=[your email]`

Refactor add_admin_role rake task to use env variable

---

app/jobs/application_job.rb
app/jobs/characterize_job.rb
app/jobs/create_pyramid_tiff_job.rb
config/initializers/hyrax.rb
config/settings/development.yml
lib/active_job/queue_adapters/better_active_elastic_job_adapter.rb
spec/lib/active_job/queue_adapters/better_active_elastic_job_adapter_spec.rb
spec/support/active_elastic_job_config.rb

Make the changes to `ActiveJob::QueueAdapters::BetterActiveElasticJobAdapter` required to support AWS SQS FIFO queues

Support FIFO queues in ActiveJob

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/indexers/image_indexer.rb
app/models/concerns/edtf_date_validator.rb
app/models/image.rb
app/models/solr_document.rb
app/presenters/hyrax/image_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/factories/images.rb
spec/indexers/image_indexer_spec.rb
spec/models/concerns/edtf_date_validator_spec.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/342
* validates (batch and UI) that there is at least one date_created value present, and that the values are in edtf format
* indexes the humanized/display version as `date_created_display_tesim` for use by the front end/UI
Notes: 
This is affected by this bug: https://github.com/nulib/next-generation-repository/issues/486 where you receive an error if you try to correct and resubmit a failed validation in the UI. We're not sure yet whether this is a Hyrax or Donut bug. Until we can address this, the workaround is to make sure you get the format correct first time around. Batch should work fine.

validate edtf format for date_created and index display value

---

app/controllers/catalog_controller.rb

Fixes  https://github.com/nulib/next-generation-repository/issues/485
* Allow users to locate works by entering id or accession number into search box

adds accession_number and id to all_fields for search

---

.gitignore
app/indexers/donut/collection_indexer.rb
config/initializers/donut_collection_indexer.rb
spec/indexers/donut/collection_indexer_spec.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/504
* Indexes the iiif url for the collection thumbnail as `thumbnail_iiif_url_ss`

index iiif path for collection thumbnail

---

config/authorities/licenses.yml
spec/models/concerns/license_validator_spec.rb

Fixes https://github.com/nulib/next-generation-repository/issues/503
* Adds new Creative Commons 4.0 licenses
* Sets outdated licenses to inactive

update licenses to Creative Commons 4.0

---

app/batch/importer/factory/object_factory.rb

Fixes https://github.com/nulib/next-generation-repository/issues/505
* .csv file can be uploaded anywhere in the bucket, as long as paths in 'file' are relative to the csv file

fixes bug finding relative file path

---

app/batch/importer/csv_importer.rb
spec/batch/importer/csv_importer_spec.rb
spec/fixtures/csv/malformed.csv

Fixes https://github.com/nulib/next-generation-repository/issues/518
• Fixes issues where if a malformed csv file was ingested, it appeared to the user that the batch did not run at all.
• Rescues a `CSV::MalformedCSVError` and creates an error for the batch that will display to the user in the UI. 
• Updated spec for CSVImporter

handle and display malformed csv error to user

---

Gemfile
Gemfile.lock
README.md
app/assets/javascripts/application.js
app/assets/javascripts/hyrax/save_work/save_work_control.es6
app/assets/javascripts/hyrax/save_work/validation_service.es6
app/controllers/validation_controller.rb
app/models/concerns/accession_number_validator.rb
app/models/concerns/preservation_level_validator.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/routes.rb
lib/tasks/donut.rake
spec/controllers/validation_controller_spec.rb
spec/javascripts/helpers/jasmine-jquery.js
spec/javascripts/support/jasmine.yml
spec/javascripts/support/jasmine_helper.rb
spec/javascripts/validation_service_spec.js

Fixes https://github.com/nulib/next-generation-repository/issues/486
* works around the problem with resubmitting a failed form validation by using the `Donut::ValidationService` to validate via JavaScript before the form is submitted.
* Adds `app/controllers/validation_controller.rb` to handle validation requests
* Adds `app/assets/javascripts/hyrax/save_work/validation_service.es6` to handle the JavaScript validation
* overrides Hyrax `app/assets/javascripts/hyrax/save_work/save_work_control.es6` to use the validation service on submit
* Adds Jasmine and a JavaScript test + updates readme
* Makes accession_number read only on edit form
* Removes the duplicate *NUL Subject* field from image display

fixes form validation issues

---

app/controllers/catalog_controller.rb
app/indexers/image_indexer.rb
app/presenters/hyrax/characterization_behavior.rb
config/initializers/delegate_metadata_to_file_set_presenter.rb
spec/indexers/image_indexer_spec.rb

Fixes https://github.com/nulib/next-generation-repository/issues/459
* indexes the technical metadata for `FileSet.characterization_proxy` at the (parent) Image level so it can be exposed in facets, and searched.
Co-authored-by: Brendan Quinn <brendan-quinn@northwestern.edu>

Adds technical metadata to facets

---

app/views/hyrax/dashboard/collections/_form_branding.html.erb

* Temporarily disable collection branding form so as not to cause confusion. 
* Provide message linking to 'Discovery' tab with instructions to choose representative thumbnail for the collection instead.
Co-authored-by: Brendan Quinn <brendan-quinn@northwestern.edu>

temporarily hides collection branding form

---

Gemfile

This prevents devs from having to install ClamAV locally in order to get the environment to load.

Move ClamAV gem to production group

---

app/models/user.rb
config/initializers/hyrax.rb
config/settings.yml
spec/models/user_spec.rb

Fixes an issue where Hyrax will raise an exception attempting to create a system user in a password-less configuration.

Override how Hyrax creates system users and create default configuration

---

app/controllers/catalog_controller.rb
app/indexers/image_indexer.rb
app/models/concerns/hyrax/file_set/characterization.rb
app/models/solr_document.rb
app/presenters/hyrax/characterization_behavior.rb
app/services/donut/characterization_service.rb
config/initializers/capture_device_alias_to_model.rb
config/initializers/delegate_metadata_to_file_set_presenter.rb
config/initializers/extend_file_set_indexer.rb
spec/models/solr_document_spec.rb
spec/services/donut/characterization_service_spec.rb

fixes https://github.com/nulib/next-generation-repository/issues/542 
`capture_device` already exists in hydra works, so instead of creating another one, i've aliased `model` to `capture_device` and made `model` visible in the UI

alias capture_device to model, make it visible in the ui

---

app/views/hyrax/file_sets/_versioning.html.erb

* Per Laura and David, disable versions until bugs are fixed and provide help text suggesting to delete and re-ingest the file instead. 
* overrides `app/views/hyrax/file_sets/_versioning.html.erb` from Hyrax
References https://github.com/nulib/next-generation-repository/issues/476

disable Hyrax fileset versioning

---

app/batch/importer/csv_parser.rb
spec/batch/importer/csv_parser_spec.rb

References https://github.com/nulib/next-generation-repository/issues/567
Fixes https://github.com/nulib/next-generation-repository/issues/584
Allows users to add the header 'visibility' to the batch spreadsheet with one of these values:
- 'open' for Public
- 'authenticated' for Institution
- 'restricted' for Private
* Add visibility to valid headers in `csv_parser.rb`
* Add visibility to list of single valued fields in `csv_parser.rb`

Allow visibility in batch manifest

---

app/controllers/validation_controller.rb

Fixes https://github.com/nulib/next-generation-repository/issues/586
* exclude `member_of_collections_attributes` from validation in order to avoid an `ActiveFedora::UnknownAttributeError` error.

Fixes adding to collection when creating new work bug

---

app/services/common_indexers/admin_set.rb
config/initializers/admin_set_indexing.rb
spec/lib/hyrax/controlled_vocabularies/location_spec.rb
spec/models/admin_set_spec.rb
spec/models/image_spec.rb

- Add `CommonIndexers::AdminSet` class that indexes model, title, description and visibility
- Add model spec for AdminSet
- Refactor Image model to be less coupled to fixture data.

Add AdminSet indexing functionality and spec

---

.rubocop.yml
.rubocop_todo.yml
app/services/common_indexers/image.rb
lib/hyrax/controlled_vocabularies/location.rb
spec/lib/hyrax/controlled_vocabularies/location_spec.rb

* updates common indexer to include fileset_iiif_urls, represetnative file iiif url (without dimensions), resource type and id. (all needed for front end display)
* Also implement a guard clause to prevent an error running `to_common_index` in case bad data `www.geonames` instead of `sws.geonames` is already stored in an existing record.

Add resource_type, file iiif urls, and id to image indexer

---

app/models/controlled_vocabularies/base.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/601
* adds `::RDF::Vocab::GEONAMES.name` to the `rdf_label` configuration so geonames can find labels in Subject Geographical

configure rdf_label to handle geonames

---

app/services/common_indexers/image.rb

fixes https://github.com/nulib/next-generation-repository/issues/617
I'm not sure if the box/folder fields should be moved to `extra_fields` or if they'll be used for any additional work types

indexing fields requested by the front end mockups

---

app/controllers/validation_controller.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/625

exclude work_members_attributes from edit validation check

---

app/models/image.rb
app/services/donut/duplicate_accession_verification_service.rb
spec/models/batch_item_spec.rb
spec/models/solr_document_spec.rb
spec/services/donut/duplicate_accession_verification_service_spec.rb

Fixes: https://github.com/nulib/next-generation-repository/issues/630
* index accession number as `_ssim` rather than `_tesim` which was causing the accession number to be tokenized at dashes and find duplicates for a partial match like "inu-wint-26-52" and  "inu-wint-26-52-placeholder" and then skip the batch item.

Fixes bug where partial accession match is considered duplicate

---

app/services/common_indexers/base.rb
app/services/common_indexers/image.rb

Fixes https://github.com/nulib/next-generation-repository/issues/638
* also removed `fileset_iiif_urls` from index as they are not being used, and probably shouldn't since they don't currently respect visibility

index human readable version edtf date for front end to display

---

.docker-stack/nextgen-development/docker-compose.yml
Rakefile
lib/tasks/docker.rake
lib/tasks/donut.rake

Adds a `rake donut:setup_and_specs` task to make using devstack easier without breaking the standalone docker-stack build.

Tweak the configs and rake tasks to work well with the docker-stack gem *and* standalone devstack.

---

app/controllers/catalog_controller.rb
app/forms/hyrax/image_form.rb
app/models/schemas/common_metadata.rb
app/models/solr_document.rb
app/models/vocab/donut.rb
app/presenters/hyrax/image_presenter.rb
app/services/common_indexers/image.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/factories/images.rb
spec/forms/hyrax/image_form_spec.rb
spec/models/solr_document_spec.rb
spec/support/shared_examples/a_model_with_common_metadata.rb

fixes https://github.com/nulib/next-generation-repository/issues/565
i left the legacy identifiers field editable since i figured it'd be nice for users of the app to be able to add/edit without having to go through the devs, but i'm open to changing it

adding in legacy ids field

---

app/models/schemas/core_metadata.rb
spec/models/image_spec.rb
spec/support/shared_examples/a_model_with_nul_core_metadata.rb

Fixes https://github.com/nulib/next-generation-repository/issues/627
* changes `license` predicate from `http://purl.org/dc/terms/rights`  to `http://purl.org/dc/terms/license` per spreadsheet: https://docs.google.com/spreadsheets/d/1PBvp9FJAvG6JIP6RZwmiZSDhgYLQ6VRSknUnkodEH8Q/edit#gid=39640035

Overrides predicate defined in Hyrax for license

---

app/models/schemas/core_metadata.rb
spec/support/shared_examples/a_model_with_nul_core_metadata.rb

fixes https://github.com/nulib/next-generation-repository/issues/673
when saving a record and filling out the language field, the predicate shows up as a dc/terms/language predicate now.

update language predicate to match jens spreadsheet

---

README.md
app/builders/s3_manifest_helper.rb
app/helpers/application_helper.rb
app/models/s3_manifest_ability.rb
app/presenters/hyrax/displays_image.rb
app/presenters/s3_iiif_manifest_presenter.rb
app/services/common_indexers/image.rb
app/services/iiif_manifest_service.rb
app/views/hyrax/base/_representative_media.html.erb
config/initializers/hyrax.rb
config/locales/hyrax.en.yml
config/settings/development.yml
config/settings/test.yml
spec/fixtures/files/manifest.json
spec/models/image_spec.rb
spec/models/s3_manifest_ability_spec.rb
spec/services/iiif_manifest_service_spec.rb

*  Adds `IiifManifestService` that provides a`IiifManifestService.write_manifest(id)` method to write a manifest to an s3 bucket for a given work.
Since we can't figure out the best place to put this at the moment, we're thinking we merge this, and make sure that the parts that actually write the manifest to the buckets work, and the service can be called directly.

Adds service to write iiif manifest to s3

---

app/services/common_indexers/image.rb

fixes https://github.com/nulib/next-generation-repository/issues/759
Adds to Elasticsearch indexing:
- `date_modified`
-  `date_uploaded`
-  `related_material`
- `scope_and_contents`
- `series`
- `table_of_contents`
- `based_near` (Location) 
- Adds `subject_temporal` to subject indexing

Index date_created and date_modified and other Image model properties in Elasticsearch

---

app/services/common_indexers/image.rb

CommonIndexers::Image#representative_file can handle arbitrarily nested representative works.
Fixes https://github.com/nulib/next-generation-repository/issues/779
Co-authored-by: Karen Didrickson <karendid@gmail.com>

CommonIndexers::Image#representative_file refactor

---

app/services/common_indexers/image.rb

After deploying a solution for https://github.com/nulib/next-generation-repository/issues/779, we discovered you cannot use `file_set.files.first` to obtain the id of the .tif as described here: https://github.com/nulib/next-generation-repository/issues/797
* use `file_set.original_file.id` instead of`file_set.files.first.id`

Use original_file instead of files.first for FileSet representative file

---

Gemfile
Gemfile.lock
README.md
app/controllers/hyrax/images_controller.rb
app/jobs/create_pyramid_tiff_job.rb
app/services/common_indexers/image.rb
app/services/iiif_derivative_service.rb
config/database.yml
config/environments/development.rb
config/initializers/sidekiq.rb
config/routes.rb
config/settings/development.yml

fixes https://github.com/nulib/next-generation-repository/issues/760
fixes https://github.com/nulib/next-generation-repository/issues/718
* Creates a public route for manifests and adds url to Elasticsearch index. Ex: `"iiif_manifest": "http://devbox.library.northwestern.edu/public/55/ae/ff/31/-c/90/3-/49/99/-8/b5/9-/a6/00/ac/b2/f2/fd-manifest.json"`
* Manifests are shown for Public/NetId works only - but each manifest will contain ALL FileSets (including private ones)
* Uses `file_set.id` instead of the file id (`file_set.files.first.id`) to name the pyramidal .tif location to get around the issue of the file id not being available at index time.
* Adds sidekiq to development dependencies so that functionality that depends on async jobs can be adequately tested.
* Jobs will still run …

Use the FileSet ID for the pyramid TIFF location and IIIF ID

---

app/controllers/hyrax/images_controller.rb

`prepend_before_action { params[:id].delete!('/') }` is causing problems for Adam. Removing for now since we're not using yet, @mbklein can reimplement when he's ready.

Remove action removing slashes from id

---

Dockerfile
config/puma_container.rb

Just let puma write to stdout instead of logging to a file inside the container

Remove /var/log/puma and just log to stdout

---

config/initializers/operation_workaround.rb

Just return a dummy for a missing Hyrax::Operation because we do not care.

Fix the Hyrax::Operation issue once and for all

---

app/controllers/batches_controller.rb
app/models/ability.rb
app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
spec/factories/admin_sets.rb
spec/factories/collections.rb
spec/factories/images.rb
spec/models/ability_spec.rb

Fixes https://github.com/nulib/next-generation-repository/issues/733
* Allow users with 'rdc_managers' role to view Batches in Admin Dashboard
* Remove `DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 5.2.`

Allow rdc_managers role to see Batch in Admin Dashboard

---

app/controllers/hyrax/single_use_links_controller.rb
app/models/ability.rb
app/views/hyrax/file_sets/show.html.erb

Fixes https://github.com/nulib/next-generation-repository/issues/847
* Overrides Hyrax's `app/controllers/hyrax/single_use_links_controller.rb` and `app/views/hyrax/file_sets/show.html.erb` to allow "unit_viewers" to create `single_use_links`

Allow unit_viewers to create single_use_links

---

app/jobs/create_pyramid_tiff_job.rb

partially fixes https://github.com/nulib/next-generation-repository/issues/856
This PR addresses one of the two issues reported in next-generation-repository#856 by making sure pyramid TIFF derivatives never exceed [sharp](https://github.com/lovell/sharp)'s internal pixel limit.

Limit pyramid TIFFs to 16383x16383 pixels

---

app/models/batch_item.rb
app/services/donut/vocabulary_validation_service.rb
spec/models/batch_item_spec.rb
spec/services/donut/vocabulary_validation_service_spec.rb

fixes https://github.com/nulib/next-generation-repository/issues/717
* Validates that controlled vocabularies only contain uri's in formats described here: https://github.com/nulib/next-generation-repository/wiki/URI-Construction-for-Controlled-Vocabularies

Check that controlled vocab uris in batch are valid format

---

solr/blacklight_conf/schema.xml
solr/conf/schema.xml

`StandardFilterFactory` filters were deprecated in Solr 7. Removing these filters will prevent an error when upgrading to Solr 8. See https://github.com/projectblacklight/blacklight/pull/2017 for more information.

Remove deprecated StandardFilterFactory Solr filters from Solr config

---

app/controllers/application_controller.rb

Removes `discard_flash_if_xhr` Blacklight deprecation warning prior to upgrading to blacklight 7.x

Fixed deprecation warning: discard_flash_if_xhr

---

Gemfile
Gemfile.lock

Removes the unused `solr_wrapper`, `fcrepo_wrapper` and `sidekiq` gems from the Gemfile.

Remove '*_wrapper' dependencies and sidekiq from the Gemfile

---

Dockerfile

This is a container build-only PR, so there's not much use waiting for tests to pass.

Add FITS dependencies to LD library path

---

app/services/donut/file_set_derivatives_service.rb

`CreatePyramidTiffJob` no longer requires the `file_id` parameter.

Use new method signature for CreatePyramidTiffJob

---

app/services/ark_minting_service.rb

Wrap ARK/EZID API calls so errors can be caught and logged without raising an exception.

Make ARK generation more fault tolerant

---

README.md
app/services/common_indexers/image.rb

* Only indexes collection information on the Image document in Elasticsearch if the collection is of the type that matches the `Settings.nul_collection_type`

Only index collections of type NUL Collection in Elasticsearch Image documents

---

app/models/collection.rb
config/settings/test.yml

* Just don't index Collections that aren't "NUL Collection/s" at all rather than relying on Glaze to filter them out.
* This is instead of this: https://github.com/nulib/next-gen-front-end-react/commit/d2d233f86458bbb0d8807b27ba0eafb5ba7120ff
since staging and prod are named differently....

Only index a collection if its an NUL collection

---

app/controllers/visibility_controller.rb
app/jobs/public_collection_job.rb
app/jobs/public_image_job.rb
app/views/hyrax/dashboard/collections/_show_add_items_actions.html.erb
config/routes.rb
spec/controllers/visibility_controller_spec.rb
spec/factories/images.rb
spec/jobs/public_collection_job_spec.rb
spec/jobs/public_image_job_spec.rb
spec/rails_helper.rb

To test the feature, go to the Collections dashboard page, choose a collection and click the "Make Images Public" button. It should kick off jobs that change the visibility of each `restricted` or `authenticated` Image and its FileSets to `open`.

244 public works

---

README.md

* Make it easier to find information about Collection Type indexing (restricted to NUL Collection(s) in Elasticsearch ) by linking to the wiki from the readme

Add link to wiki page about Collection Type indexing from Readme

---

app/jobs/image_visibility_job.rb
spec/jobs/image_visibility_job_spec.rb

- Manually set image `date_modified` during `ImageVisibilityJob`
- Fixes issue where Glaze "Recently added and updated items" does not contain works which had visibility updated using the change image visibility job.

Set the date_modified on visibility change

---

app/services/common_indexers/base.rb

- "uuuu" is an `EDTF::Unknown` type and throws an error when you try to call `iso8601` or `year` during expansion for `expanded_date` and `year` fields.
- I'm not sure we're using the expanded date/year at all. I think we initially used the year for the date slider, which has been removed. I'll start a discussion in the issue about whether we can remove these completely but for now they just won't have a value when the date is unknown - which I think makes sense since the date is unknown.

Check for supported methods while expanding dates during index

---

app/batch/importer/factory/object_factory.rb
app/jobs/import_url_job.rb

Since this PR involves a new Hyrax override, `import_url_job.rb` shows as an added file without changes. Substantive changes to the job can be seen in [this commit](https://github.com/nulib/donut/commit/b16b474e997dd8e2964665d6a9e3abb6a7281301).

allow direct s3 import

---

.gitignore
Gemfile
Gemfile.lock
README.md
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/sessions_controller.rb
app/models/user.rb
config/initializers/omniauth.rb
config/puma/development.rb
config/routes.rb
config/settings/test.yml

- Adds [`omniauth-nusso`](https://github.com/nulib/omniauth-nusso) along with updated routes and callbacks_controller
- Removes `omniauth-openam`
- Updates README for `config/ssl` instructions to run SSL locally
- Upgrade puma to `4.3.3`, includes `config/puma/development.rb` configuration to run SSL locally

Add agentless SSO using omniauth-nusso strategy

---

Gemfile.lock

See https://github.com/nulib/common-indexer/pull/11 for more information about `common_indexer v0.5.1`

Update common_indexer gem to v0.5.1

---

Gemfile
Gemfile.lock

Updating `omniauth-nusso` to `0.1.3` will prevent JSON parsing errors from directory search responses. See https://github.com/nulib/omniauth-nusso/pull/1 for more information.

Update omniauth-nusso to v0.1.3

---

Gemfile
Gemfile.lock

Current failing behavior:
Fixed with upgrade to `qa` v.5.5.1:
Note: you'll need to run `bundle install` locally due to changes in the `Gemfile`.

Remove pinned version of questioning authority in order to upgrade to v5.5.1

---

.rubocop.yml
Gemfile
Gemfile.lock
app/services/common_indexers/file_set.rb
config/settings/test.yml
spec/services/common_indexers/file_set_spec.rb

This PR adds `digest`, `simple_title`, `height`, `width`, `mime_type`, and `original_checksum` to the common index for FileSets. `simple_title` is used instead of `title`, because the mapping expects `title` to be a complex field (with a `primary` and an `alternate`), and that doesn't apply to FileSets.

Add additional fields to FileSet index

---

app/services/donut/migration_service.rb
spec/services/donut/migration_service_spec.rb

Meadow will raise errors during migration because of deprecated EDTF dates that use "u" for unknown such as `202u`. During migration, the dates will be translated to use the current valid "X" character instead.
Note: you can save some time in the tests by just running `bundle exec rspec spec/services/donut/migration_service_spec.rb`

Replace 'u' with 'X' in EDTF dates during migration
